### ISSUE TITLE
feat(k3s,kubeadm): multiple database options (support for etcd)

### ISSUE THREAD

**Issue by Horiodino** [ksctl/ksctl#127]
As ksctl is based on k3s ha cluster , so its important to also have database right.
right now ksctl supports MySQL , while there are multiple databases k3s supports  
the main point is to add additional database option that developers can select while creating the 
cluster.

what problem it can solve ?
by adding support for multiple database , developers doesn't need to rely on any other 
thing , what if they need to use etc instead of sql ? then simply then can use flags then mention the database they want to use
so it brings more flexibility and more user friendly .

# Describe alternatives you've considered💠

# Provider in question
- [ ] Civo
- [ ] AWS
- [ ] Local
- [ ] Azure

**Comment by dipankardas011** [comment]
@AvineshTripathi 👀

**Comment by dipankardas011** [comment]
@Horiodino we can add one option only for database to use 
Currently we are planning for the etcd to be used for both k3s and kubeadm based self-managed clusters

**Comment by Horiodino** [comment]
> @Horiodino we can add one option only for database to use i.e. one datastore type for each kubernetes distributions Currently we are planning for the etcd to be used for both k3s and kubeadm based self-managed clusters

Na i think i asked in wrong way let me explain . we know one data store type for each kubernetes distro  .but what i am saying is that it should be optional to end user to select the database that he wanted as data store. 
im not saying multiple database in kubernetes distributions . the configuration should be same just we will add additional option . thats it.

**Comment by dipankardas011** [comment]
We can leave the management of the tls certs on the etcd to decide
Refer: [auto-tls](https://etcd.io/docs/v3.4/op-guide/clustering/#automatic-certificates)

**Comment by dipankardas011** [comment]
need to create scripts to make the etcd HA setup

**Comment by dipankardas011** [comment]
https://kubernetes.io/docs/setup/production-environment/tools/kubeadm/setup-ha-etcd-with-kubeadm/#setting-up-the-cluster

**Comment by dipankardas011** [comment]
https://etcd.io/docs/v3.2/op-guide/security/
