### ISSUE TITLE
[ACTION-TRACKING] store instance type data for both managed and self-managed

### ISSUE THREAD

**Issue by Horiodino** [ksctl/ksctl#246]
# Why do we need it?
 there can be different instance types for control plane, worker nodes, load balancers, and databases , based on the user requirement , save the info in the cloud-state 

# what are the sub-goals
- [ ] find suitable place from where you can get the instancetype for the vms created
- [ ] civo provider
- [ ] azure provider
- [ ] aws provider
- [ ] 

## Additional context

Check [Contribution's guidelines](https://kubesimplify.github.io/ksctl/docs/contributions)

**Comment by AniketNS** [comment]
I'll try to solve this issue. can you assign me this @dipankardas011 ?

**Comment by dipankardas011** [comment]
> I'll try to solve this issue. can you assign me this @dipankardas011 ?

Here is the catch this issue will take a bit longer to merge as this issue is directly dependent on #255 .
Still you can raise a PR. Just wanted to be clear upfront

**Comment by AniketNS** [comment]
NP. I just want to contribute

**Comment by dipankardas011** [comment]
we need to store the instanceType in the stateDocument struct so that later we can refer to that when we get the state data

**Comment by dipankardas011** [comment]
@AniketNS are you available to work on this issue?
