### ISSUE TITLE
enhancement(bootstrap): Improve the bootstrap error handling and addition of concurrency

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#288]
# Why do we need it?
as there is a depependency as follows

```mermaid
flowchart TD
LB -->|Depends On| A[START]
DS -->|Depends On| A

CP0(ControlPlane-0) --> |Depends On| LB(LoadBalancer)
CP0(ControlPlane-0) --> |Depends On| DS(DataStore-0..P)

CPN(ControlPlane-1..N) --> |Depends On| CP0
WPM(WorkerPlane-0..M) --> |Depends On| CP0
```

> [!NOTE]
> In a given level, all execution can be parallelised

# What it will bring?
Plan in knowledge docs [Link](https://docs.google.com/document/d/1X7LHlwRENBGIEFDyozRippI-xorBTqOGVjiDeGjYAMI/edit#heading=h.gdm5q8f6s5hl)

## Plan
- [x] To parallelise the creation time of bootstrap process #318 
- [ ] To add better script execution logic as mentioned in knowledge docs

## Additional context

Check [Contribution's guidelines](https://docs.ksctl.com/docs/contribution-guidelines/)

**Comment by MRafaydev** [comment]
Hey @dipankardas011 can you please guide me how I can test this script locally after changes?

**Comment by dipankardas011** [comment]
> Hey @dipankardas011 can you please guide me how I can test this script locally after changes?

For testing you can use `test/e2e/`
and use specific cloud provider
lets say azure
```bash
export .... # things for the azure

export LOG_LEVEL="DEBUG" # if you want to have debug level of logs for the e2e
cd test/e2e
go run . -op create -file azure/create-ha.json
```

 like this a lot of thim check in `test/e2e-jenkins` will help

**Comment by dipankardas011** [comment]
Also just wait for this particular issue problem and solution to be finilaized then you can start working

you can check the latest discord message as it is related to this issue

**Comment by dipankardas011** [comment]
> you can check the latest discord message as it is related to this issue

for that you can refer to this https://docs.google.com/document/d/1X7LHlwRENBGIEFDyozRippI-xorBTqOGVjiDeGjYAMI/edit#heading=h.gdm5q8f6s5hl
