### ISSUE TITLE
enhancement(CI)!: Improve the CI pipeline

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#296]
# Why do we need it?
the currently there is no gh action for automating the release when there is a new tag created. (use github api) Refer: [Blog post](https://rtcampblogsdipankardas.wordpress.com/2024/02/15/seamless-devops-automating-deployment-and-releases-with-github-actions/)
also we need to move on from using `docker.io/kubesimplify/ksctl:slim-v1` -> `ghcr.io/ksctl/ksctl:latest-agent` for this as well the above blog has steps
(NOTE: for every new commit in main branch We need to push the httpserver/ directory docker container to the ghcr) Workflow in focus for this is https://github.com/ksctl/ksctl/blob/main/.github/workflows/docker.yaml

also we are having issues with the main branch checks, when the PR is merged

# What it will bring?
create a gh workflow for every tag push and also attach reviewer for it to `dipankardas011`. before the release workflow starts

update the gh workflow / modify the existing to also check in main branch

## Additional context

Check [Contribution's guidelines](https://ksctl.github.io/docs/docs/contribution-guidelines/)

**Comment by Aditya-Narayan-Nayak** [comment]
I can contribute on this issue

**Comment by dipankardas011** [comment]
sure lets meet at 6pm

**Comment by dipankardas011** [comment]
Added the github release workflow [992c918](https://github.com/ksctl/ksctl/commit/992c9181da6abf776e4318ced24cf53129a3d7d5)

**Comment by dipankardas011** [comment]
added the release on tag push https://github.com/ksctl/ksctl/commit/b271688351e2c95cd2b4a80bc38b976ae5ebfbc8
