### ISSUE TITLE
[Enhancement Proposal]: E2E-CI Runner Auto Create and Delete for self hosted runner

### ISSUE THREAD

**Issue by iamimmanuelraj** [ksctl/ksctl#380]
### Enhancement Title

Auto Create/Delete of Self Hosted Runner for Testing the core

### Summary of the Enhancement

This will make the cost of the test servers way cheap because it is created and destroyed only when needed.

### Motivation and Goals

Goal : Reduce CO2 and Money
Motivation : @dipankardas011 

### Detailed Design

We can use terraform to provision Infra for VMs and ansible to make a server setup (to github custom runner) and use rest api to attach the vm to the github actions custom runners. Once done we can easily destroy the infra and the custom runner entry once done.

**Advantages**
reduce the ip and address and the VM configuration in github
cost reduction
cloud credits will get over  so need to reduce the long running tasks

### Scope of changes

- [ ] Cli
- [ ] UI
- [ ] Docs

### Agreement

- [X] I agree to engage in constructive discussion and follow the Contribution Guidelines.

**Comment by dipankardas011** [comment]
Thanks @iamimmanuelraj for creating this issue 😄

**Comment by dipankardas011** [comment]
## IMportant docs
https://docs.github.com/en/rest/actions/self-hosted-runners?apiVersion=2022-11-28
https://docs.github.com/en/actions/hosting-your-own-runners/managing-self-hosted-runners/autoscaling-with-self-hosted-runners#authentication-requirements

**Comment by dipankardas011** [comment]
```
./config.sh --url https://github.com/ksctl/ksctl --token XYZZZ --unattended --labels e2e
```
