### ISSUE TITLE
enhancement: Add a lock on the config files during write operation

### ISSUE THREAD

**Issue by dipankardas011** [ksctl/ksctl#80]
# Is your feature request related to a problem?📖 

For atomacity and only one operation at a time create or delete not both at the same time

# Describe the solution you'd like 👨‍💻👩‍💻

some kind of file lock when one file is being written to if the lock file is present we will raise a panic or error as return which will mark it as failure due `the config is held by another process` 

# Describe alternatives you've considered💠

**Comment by riteshsonawane1372** [comment]
Similar to what Terraform does to its state file?

**Comment by dipankardas011** [comment]
> Similar to what Terraform does to its state file? 

It's not just terraform but all software do it

**Comment by dipankardas011** [comment]
Currently, this issue still needs to be looked at

The best place I think would be to check the api/storage/*

**Comment by dipankardas011** [comment]
This needs to be added!!!

**Comment by dipankardas011** [comment]
Its partially done
